# config.yml
backend:
  name: git-gateway
  repo: search-rug/search-rug.github.io
  branch: main
  identity_url: "https://search-rug.netlify.app/.netlify/identity"
  gateway_url: "https://search-rug.netlify.app/.netlify/git"
  site_domain: "https://search-rug.netlify.app"
media_folder: "assets/uploads"
collections:
  - name: "team"
    label: "Team"
    folder: "_team"
    create: true
    editor:
      preview: false
    fields:
      - { name: "title", widget: string }
      - { name: "position", widget: string }
      - name: "status"
        widget: "object"
        fields:
          - name: "promoted"
            widget: "boolean"
            hint: "Appear in home page"
            default: false
          - name: "former"
            widget: "boolean"
            hint: "Former group member"
            default: false
          - name: "group_graduate"
            widget: "boolean"
            hint: "Graduated PHD student"
            default: false
      - name: "contact"
        widget: "object"
        fields:
          - { name: "homepage", required: false }
          - { name: "email" }
          - { name: "phone", required: false }
          - { name: "room", required: false }
      - name: "social"
        widget: "object"
        fields:
          - { name: "linkedin", required: false }
          - { name: "twitter", required: false }
          - { name: "mastadon", required: false }
          - { name: "github", required: false }
      - name: "publications"
        widget: "object"
        fields:
          - { name: "pure", required: false }
          - { name: "gscholar", required: false }
          - { name: "orcid", required: false }
          - { name: "dbpl", required: false }
      # TODO: add (research) fields and topics fields

  - name: "news"
    label: "News"
    folder: "_news"
    create: true
    editor:
      preview: false
    fields:
      - { name: "title" }
      - { name: "keywords", widget: "list" }
      - { name: "date", widget: "date" }
      - { name: "body", widget: "markdown" }

  - name: "courses"
    label: "Courses"
    folder: "_courses"
    create: true
    editor:
      preview: false
    fields:
      - { name: "code", label: "Course Code" }
      - { name: "name" }
      - { name: "ocasys", label: "Ocasys Link" }
      - name: "coordinators"
        widget: "relation"
        required: false
        collection: "team"
        value_field: "title"
        search_fields: ["title"]
        multiple: true
      - name: "lecturers"
        widget: "relation"
        required: false
        collection: "team"
        value_field: "title"
        search_fields: ["title"]
        multiple: true
      - name: "external_coordinators"
        widget: "list"
        required: false
        fields:
          - { name: "name" }
          - { name: "email" }
      - name: "external_lecturers"
        widget: "list"
        required: false
        fields:
          - { name: "name" }
          - { name: "email" }

  - name: "projects"
    label: "Research Project"
    folder: "_projects"
    create: true
    editor:
      preview: false
    fields:
      - { name: "title" }
      - { name: "short" }
      - { name: "archived", widget: "boolean" }
      - { name: "homepage", required: false }
      - name: "logo"
        widget: "image"
        media_folder: "/images/projects"
        allow_multiple: false
        required: false
      - { name: "body", widget: "markdown", required: false }
      - name: "members"
        widget: "relation"
        collection: "team"
        value_field: "title"
        search_fields: ["title"]
        multiple: true
      - name: "funding"
        widget: "list"
        required: false
        fields:
          - { name: "agency" }
          - name: "shortname"
            # TODO: correct? funding agency or funding instrument?
            hint: "Shortname or acronym for funding agency."
          - { name: "number" }

  - name: "sprojects"
    label: "Student Project"
    folder: "_sprojects"
    create: true
    editor:
      preview: false
    fields:
      - { name: "title" }
      - { name: "short" }
      - { name: "archived", widget: "boolean" }
      - { name: "category" }
      - name: "keywords"
        widget: "list"
        hint: "A comma separated list of project keywords. Should give students an intuition for what the project is about."
      - name: "types"
        widget: "select"
        options: ["MSc", "BSc", "MSc Int"]
        multiple: true
      - name: "supervisors"
        widget: "relation"
        collection: "team"
        value_field: "title"
        search_fields: ["title"]
        multiple: true
      - { name: "is_group", widget: "boolean" }
      - { name: "available", widget: "boolean" }
      - { name: "posted", widget: "date" }
      - { name: "body", widget: "markdown", required: false }

  - name: "pages"
    label: "Pages"
    files:
      - name: "index"
        label: "Landing"
        file: "index.md"
        editor:
          preview: false
        fields:
          - { name: "title" }
          - { name: "description" }
          - name: "intro_image"
            widget: "image"
            media_folder: "/images/illustrations"
            allow_multiple: false
            required: false
          - { name: "body", widget: "markdown" }

      - name: "team"
        label: "Team"
        file: "team.md"
        editor:
          preview: false
        fields:
          - { name: "title" }
          - { name: "description" }
          - { name: "body", widget: "markdown" }

      - name: "education"
        label: "Education"
        file: "education.md"
        editor:
          preview: false
        fields:
          - { name: "title" }
          - { name: "description" }
          - { name: "body", widget: "markdown" }

      - name: "contact"
        label: "Contact"
        file: "contact.md"
        editor:
          preview: false
        fields:
          - { name: "title" }
          - { name: "description" }
          - { name: "body", widget: "markdown" }
          - name: "group_leader"
            widget: "object"
            fields:
              - { name: "show", widget: "boolean" }
              - { name: "title" }
          - name: "secretariat"
            widget: "object"
            fields:
              - { name: "show", widget: "boolean" }
              - { name: "title" }
              - { name: "email" }
              - { name: "phone" }
              - { name: "fax" }
